package io.github.jhspetersson.turtlecommander.vfs

import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Assume
import org.junit.Test
import java.io.ByteArrayInputStream
import java.nio.file.Files
import java.nio.file.Path
import java.util.Base64
import java.util.zip.GZIPInputStream

class DiskImageVirtualFileSystemTest {

    private lateinit var imagePath: Path
    private var vfs: DiskImageVirtualFileSystem? = null

    @After
    fun tearDown() {
        vfs?.close()
        if (::imagePath.isInitialized) Files.deleteIfExists(imagePath)
    }

    private fun writeImage(gzippedBase64: String, extension: String): Path {
        val compressed = Base64.getDecoder().decode(gzippedBase64)
        val image = GZIPInputStream(ByteArrayInputStream(compressed)).use { it.readAllBytes() }
        val path = Files.createTempFile("test-", ".$extension")
        Files.write(path, image)
        return path
    }

    private fun assertExtractsTestFat(diskVfs: DiskImageVirtualFileSystem) = runBlocking {
        assertTrue(diskVfs.isReadOnly)
        val rootEntries = diskVfs.listFiles(diskVfs.root).filter { !it.isParentLink }
        assertNotNull(rootEntries.find { it.name == "hello.txt" })
        assertNotNull(rootEntries.find { it.name == "sub" && it.isDirectory })
        assertEquals("hello disk image", Files.readString(diskVfs.getPath("/hello.txt")))
        assertEquals("nested content", Files.readString(diskVfs.getPath("/sub/nested.txt")))
    }

    @Test
    fun `dynamic vhd extracts via system 7-Zip`() {
        Assume.assumeTrue("system 7-Zip not installed", System7z.findBinary() != null)
        imagePath = writeImage(DYNAMIC_VHD_GZ_BASE64, "vhd")
        val diskVfs = DiskImageVirtualFileSystem(imagePath)
        vfs = diskVfs
        assertExtractsTestFat(diskVfs)
    }

    @Test
    fun `fixed vhd with footer-only cookie extracts via system 7-Zip`() {
        Assume.assumeTrue("system 7-Zip not installed", System7z.findBinary() != null)
        imagePath = writeImage(FIXED_VHD_GZ_BASE64, "vhd")
        val diskVfs = DiskImageVirtualFileSystem(imagePath)
        vfs = diskVfs
        assertExtractsTestFat(diskVfs)
    }

    @Test
    fun `vmdk extracts via system 7-Zip`() {
        Assume.assumeTrue("system 7-Zip not installed", System7z.findBinary() != null)
        imagePath = writeImage(VMDK_GZ_BASE64, "vmdk")
        val diskVfs = DiskImageVirtualFileSystem(imagePath)
        vfs = diskVfs
        assertExtractsTestFat(diskVfs)
    }

    @Test
    fun `non-vhd file is rejected silently`() {
        assertRejected("vhd")
    }

    @Test
    fun `non-vhdx file is rejected silently`() {
        assertRejected("vhdx")
    }

    @Test
    fun `non-vmdk file is rejected silently`() {
        assertRejected("vmdk")
    }

    private fun assertRejected(extension: String) {
        imagePath = Files.createTempFile("not-a-disk-image-", ".$extension")
        Files.write(imagePath, ByteArray(1024) { (it % 251).toByte() })
        try {
            DiskImageVirtualFileSystem(imagePath)
            fail("Expected construction to fail for a non-disk-image .$extension file")
        } catch (_: SilentVfsOpenException) {
        }
    }

    companion object {
        private const val DYNAMIC_VHD_GZ_BASE64 =
            "H4sICDqsfmoCA3Rlc3QudmhkAO3cwWscZRQA8C+7Ww0N2WwOSj3thzcPXXDPIihdUWxVyNYKUmG7O2mG3cykmalswIOX3v0D" +
            "+he0PXqqRYRQemlu/RM8NVA8eCg9uA7ZNBioUPBim9+Pgfd4j7k8vhneZWaYZ8mwTKchhFpYCIdqobu6cfdasnk9nAr1S2l3" +
            "fFBuTcNRbDdWq6w+mz158OjG8qh978Kzm493V+4vnX0YeGUMp8XWYLtIZofm1TfC4VlYCDGE2ezP700KXkuNGXAi7X/w0+Z4" +
            "veisD8pQayxUm18tLD6thVYVn/sxvNfr397t99b65z5b+zzG+MlH/fe7VWy2f/32hzvv/lYuff1z85c3w17ru/0/ur/vvb33" +
            "zv5f/Y20iNWV5WUcxCt5Xg6uTJI4SotxJ8avJsmgSGKaFcn2sf76JN/a2omDbLR8ems7KYoq3YnjZCeWeSy3q87VQZrFTqcT" +
            "l097e/8nF289nR+DFbOAk8fzDyfXP5a6xRDe+rB5uXl5Huf9tYsfx0OtxWP9+X74ae/8+S+rZv+bfjxzrF+vdkgAAAAAAAAA" +
            "AAAAAAAAAADgZXTikVZ4wff9nc6/9ef3f9Fb6/fOvej7/0ZoGi8A/C9tJJNJfvBPxphuDq4mJgIAr78sKcpkFId5ViZZaR4A" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAyhnmWDMt0" +
            "WqW1sPC8Wgvd1Y2715LN6+FUqF9Ku+ODcmsajmK7sVpl9dnsyYNHN5ZH7XsXnt18vLtyf+nsQ1N9dfwNoQaZFAAMIAA="

        private const val FIXED_VHD_GZ_BASE64 =
            "H4sICG2sfmoCA3Rlc3QtZml4ZWQudmhkAO3cQUsUYRgH8HE1EsNtOxQFgS/RpctCQrcISjeKtIJdKwiDVUdddp01ZwKFDh07" +
            "du4jVMeCIoigUwcvfYbwIkFHIWibXJMEg6BL5e83A88L/3kvD7zwXN5ZP/tooTmblmfrWVTo64kK+dO/UYhKef3hQXSqUnv6" +
            "rlap1kYvV6+EEC6er50ezmtx6M3t+89OvM0O3HhefL0/Wi3dWf88/HH1yOqx9a+1+UYa8jdpZ6EeptrtrD7VisNMI22WQ7je" +
            "iutpHBpJGi/tyGdb7cXFlVBPZgYHFpfiNM2XK6EZr4SsHbKlPJmrN5JQLpfD4EDEn5h4stHZdFAvYO9x/mHv+mmo64+iw+eK" +
            "k8XJbu3m1YkLYUupf0fenQ8vVcbGruVh7VYtHN2R9+YzJAAAAAAAAAAAAAAAAAAAAPA7ymFbKdrlfn+5/Ku8u/9qpVqrjO52" +
            "/78vKmovAPyV5uNWq735T8bQWKjPxToCAP+/JE6zeCZMt5MsTjL9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2Kum20k8nTWW82Uh6omizpbh" +
            "Q/Of7sYL96J9Ue/NxnBz8+PScrRdh/oOfd/T6ay9qJ788H785fjjV8cffhkZObOmq/+Ob9Tv2bwAehAA"

        private const val VMDK_GZ_BASE64 =
            "H4sICDqsfmoCA3Rlc3Qudm1kawDt3E9rHGUcB/BpWjCMNOZgi38OPmxOXhY3SdMejNC4W1patXS3rSAVJtknyZDNzrIzBhc8" +
            "9CX4OtSjN0EEz30X3nrx2JM62V2lKRUEoVjz+ewuv+H5zuw+8xsGnsvszfZH984kSXK2/iSLydTDWUnOzOvr85osJMmF+eZb" +
            "ycl9kzScTxNeNiuhnZcHoR3LnXE+qorxtXwQ06M4LvNiuNlKP7zR3uxvxEutbK2VjrJxHFbHQ7tz6c44ZlXsTUZxs3FYDItB" +
            "Xu3nO916zzI20nQldL6s6mNCf/4D9bemd+6H1ffWr4Tu7at3up3QqGJZNY8O+wfTA3r7cT6nrMrCVlbGdKXd3krTfn+7eZSP" +
            "qy+ywfX792YzDJuhsd6YRnuxOIzVeNLcmQzyYb/Oj8PVZ8L9mPWnQWvjmaSMO/XpT7ONtVmW9bNRFcfHZ3c8nPfjbLwqikH5" +
            "1AxWW+uX16+sbaxfbrgHAAAAAAAAAAAAeBEuasGp9lALAODUeVsLrP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAF6gx+9/fXiwWzZ3sypZOHcmWahfi08WkuW6/ulh8m6n9+3PvU63177RvRlCuHa111qt69I7" +
            "P3721XeNn6pX732/9MMryaPlzx//uvrLo4uP3nz8W28/L0P9HhZVyMJ2UVTZ9iCGfl4eNEO4PYhZGUM+LOP4RL47KEajSciG" +
            "/fPpaBzLst6chIM4CVURqnGd7GX5MDSbzXA+dQH/lbvfPPl96jW9gNPH/Q+n11OLusUkufDB0oOlB7M6y7t3t8Lc8uKJfLY+" +
            "vN65deuTOux92gtvnMjP1mtIAAAAAAAAAAAAAAAAAAAA4J9ohr8sJ895vr/Z/Lt8dvzHnW6v037e8//nkiXtBYD/pP04GBTT" +
            "/2QM+WG2F3UEAP7/hrGsYj/sFMMqDiv9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABeHn8ANnJL" +
            "xwAAAgA="
    }
}
